version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  web:
    image: abhuz94/rest-cities
    container_name: rest_cities
    ports:
      - 8080:3000
    volumes:
      - .:/rest-cities
volumes:
  esdata1:
    driver: local